# Generated by Django 5.0 on 2025-11-15 15:20

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='識別用の設定名', max_length=100, verbose_name='設定名')),
                ('provider_type', models.CharField(choices=[('openai', 'OpenAI'), ('azure_openai', 'Azure OpenAI'), ('anthropic', 'Anthropic Claude'), ('google', 'Google Gemini')], help_text='LLMプロバイダーの種類', max_length=20, verbose_name='プロバイダータイプ')),
                ('endpoint', models.URLField(blank=True, help_text='APIエンドポイントURL（Azure OpenAIの場合のみ）', max_length=500, verbose_name='エンドポイント')),
                ('api_key_encrypted', models.TextField(help_text='APIキー（自動的に暗号化されます）', verbose_name='APIキー（暗号化）')),
                ('model_name', models.CharField(help_text='使用するモデル名（例：gpt-4o, claude-3-5-sonnet）', max_length=100, verbose_name='モデル名')),
                ('max_tokens', models.IntegerField(default=4000, help_text='生成する最大トークン数', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200000)], verbose_name='最大トークン数')),
                ('temperature', models.FloatField(default=0.7, help_text='生成の多様性（0.0=決定的、2.0=ランダム）', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)], verbose_name='温度パラメータ')),
                ('is_active', models.BooleanField(default=True, help_text='この設定を有効にするか', verbose_name='有効')),
                ('is_default', models.BooleanField(default=False, help_text='デフォルトのプロバイダーとして使用', verbose_name='デフォルト')),
                ('use_for_client_enrichment', models.BooleanField(default=True, help_text='クライアント企業情報の自動取得に使用', verbose_name='クライアント情報取得に使用')),
                ('use_for_document_generation', models.BooleanField(default=False, help_text='ドキュメント・提案書生成に使用', verbose_name='ドキュメント生成に使用')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'AIプロバイダー',
                'verbose_name_plural': 'AIプロバイダー',
                'db_table': 'ai_providers',
                'ordering': ['-is_default', '-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_enabled', models.BooleanField(default=True, help_text='AI機能全体を有効にするか', verbose_name='AI機能を有効化')),
                ('require_confirmation', models.BooleanField(default=True, help_text='AI取得前に確認ダイアログを表示', verbose_name='確認ダイアログを表示')),
                ('allow_overwrite', models.BooleanField(default=False, help_text='既存のデータをAI取得データで上書きすることを許可', verbose_name='既存データの上書きを許可')),
                ('confidence_threshold', models.IntegerField(default=70, help_text='この値以上の信頼度のデータのみ使用（0-100）', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='信頼度しきい値')),
                ('auto_save_on_high_confidence', models.BooleanField(default=False, help_text='信頼度が90%以上の場合は自動保存', verbose_name='高信頼度時は自動保存')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'AI設定',
                'verbose_name_plural': 'AI設定',
                'db_table': 'ai_settings',
            },
        ),
        migrations.CreateModel(
            name='SearchEngineConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='識別用の設定名', max_length=100, verbose_name='設定名')),
                ('engine_type', models.CharField(choices=[('bing', 'Bing Search API'), ('google', 'Google Custom Search'), ('serper', 'Serper API')], help_text='検索エンジンの種類', max_length=20, verbose_name='検索エンジン')),
                ('api_key_encrypted', models.TextField(help_text='検索APIキー（自動的に暗号化されます）', verbose_name='APIキー（暗号化）')),
                ('search_engine_id', models.CharField(blank=True, help_text='カスタム検索エンジンID（Google CSEの場合のみ）', max_length=100, verbose_name='検索エンジンID')),
                ('max_results', models.IntegerField(default=5, help_text='取得する検索結果の最大数', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='最大検索結果数')),
                ('is_active', models.BooleanField(default=True, help_text='この設定を有効にするか', verbose_name='有効')),
                ('is_default', models.BooleanField(default=False, help_text='デフォルトの検索エンジンとして使用', verbose_name='デフォルト')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '検索エンジン設定',
                'verbose_name_plural': '検索エンジン設定',
                'db_table': 'search_engine_configs',
                'ordering': ['-is_default', '-is_active', 'name'],
            },
        ),
    ]
