# Generated by Django 5.0 on 2025-11-16 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeCategory',
            fields=[
                ('code', models.CharField(help_text='英大文字とアンダースコア推奨 (例: PROJECT_STATUS)', max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='カテゴリコード')),
                ('name', models.CharField(max_length=100, verbose_name='カテゴリ名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('is_system', models.BooleanField(default=False, help_text='True: システム固定、False: ユーザー定義可能', verbose_name='システム定義')),
                ('sort_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'コードカテゴリ',
                'verbose_name_plural': 'コードカテゴリ',
                'db_table': 'code_categories',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='CodeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='半角英数字推奨 (例: planning, active)', max_length=50, verbose_name='コード')),
                ('name', models.CharField(max_length=100, verbose_name='表示名')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='英語名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('sort_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('color', models.CharField(blank=True, help_text='UI表示用カラーコード (例: #FF5733)', max_length=20, verbose_name='色')),
                ('icon', models.CharField(blank=True, help_text='アイコン名 (例: CheckCircle)', max_length=50, verbose_name='アイコン')),
                ('parent_code', models.CharField(blank=True, help_text='階層構造の場合の親コード', max_length=50, verbose_name='親コード')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='追加属性をJSON形式で保存', verbose_name='メタデータ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='masters.codecategory', verbose_name='カテゴリ')),
            ],
            options={
                'verbose_name': 'コードマスタ',
                'verbose_name_plural': 'コードマスタ',
                'db_table': 'code_masters',
                'ordering': ['category', 'sort_order', 'code'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='code_master_categor_d2312f_idx'), models.Index(fields=['category', 'sort_order'], name='code_master_categor_a3c80d_idx')],
                'unique_together': {('category', 'code')},
            },
        ),
    ]
