# Generated by Django 5.0 on 2025-11-16 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_settings', '0002_add_provider_specific_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiprovider',
            name='use_for_client_enrichment',
        ),
        migrations.RemoveField(
            model_name='aiprovider',
            name='use_for_document_generation',
        ),
    ]
