# Generated by Django 5.0 on 2025-11-13 13:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='アクション')),
                ('description', models.TextField(verbose_name='説明')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': 'アクティビティログ',
                'verbose_name_plural': 'アクティビティログ',
                'db_table': 'activity_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
