# Generated by Django 5.0 on 2025-11-13 13:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名前')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='アバター')),
                ('role', models.CharField(choices=[('owner', 'オーナー'), ('admin', '管理者'), ('member', 'メンバー'), ('viewer', '閲覧者')], default='member', max_length=20, verbose_name='役割')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='部署')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='役職')),
                ('skills', models.JSONField(blank=True, default=list, verbose_name='スキル')),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='参加日時')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'メンバー',
                'verbose_name_plural': 'メンバー',
                'db_table': 'members',
                'ordering': ['name'],
            },
        ),
    ]
