# Generated by Django 5.0 on 2025-11-15 15:20

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('members', '0002_alter_member_avatar_alter_member_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='name',
        ),
        migrations.AddField(
            model_name='client',
            name='ai_confidence_score',
            field=models.IntegerField(blank=True, help_text='AI生成データの信頼度スコア（0-100）', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='AI信頼度'),
        ),
        migrations.AddField(
            model_name='client',
            name='ai_generated',
            field=models.BooleanField(default=False, help_text='AIで生成されたデータかどうか', verbose_name='AI生成'),
        ),
        migrations.AddField(
            model_name='client',
            name='ai_generated_at',
            field=models.DateTimeField(blank=True, help_text='AI生成実行日時', null=True, verbose_name='AI生成日時'),
        ),
        migrations.AddField(
            model_name='client',
            name='assigned_sales',
            field=models.ForeignKey(blank=True, help_text='担当営業メンバー', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_clients', to='members.member', verbose_name='営業担当者'),
        ),
        migrations.AddField(
            model_name='client',
            name='capital',
            field=models.BigIntegerField(blank=True, help_text='資本金（円）', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='資本金'),
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, help_text='市区町村名', max_length=100, null=True, verbose_name='市区町村'),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_department',
            field=models.CharField(blank=True, help_text='担当者の部署', max_length=100, null=True, verbose_name='部署'),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='担当者のメールアドレス', max_length=254, null=True, verbose_name='担当者メール'),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_mobile',
            field=models.CharField(blank=True, help_text='担当者の携帯電話', max_length=50, null=True, verbose_name='担当者携帯'),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_name',
            field=models.CharField(blank=True, help_text='先方担当者名', max_length=100, null=True, verbose_name='担当者名'),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='担当者の直通電話', max_length=50, null=True, verbose_name='担当者電話'),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_position',
            field=models.CharField(blank=True, help_text='担当者の役職', max_length=100, null=True, verbose_name='役職'),
        ),
        migrations.AddField(
            model_name='client',
            name='description',
            field=models.TextField(blank=True, help_text='主な事業内容', null=True, verbose_name='事業内容'),
        ),
        migrations.AddField(
            model_name='client',
            name='employee_count',
            field=models.IntegerField(blank=True, help_text='従業員数（人）', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='従業員数'),
        ),
        migrations.AddField(
            model_name='client',
            name='established_date',
            field=models.DateField(blank=True, help_text='会社設立日', null=True, verbose_name='設立年月日'),
        ),
        migrations.AddField(
            model_name='client',
            name='fax',
            field=models.CharField(blank=True, help_text='FAX番号', max_length=50, null=True, verbose_name='FAX番号'),
        ),
        migrations.AddField(
            model_name='client',
            name='lead_source',
            field=models.CharField(blank=True, help_text='リード獲得元（例：Web、紹介、展示会）', max_length=50, null=True, verbose_name='リード元'),
        ),
        migrations.AddField(
            model_name='client',
            name='legal_name',
            field=models.CharField(blank=True, help_text='法人の正式名称', max_length=300, null=True, verbose_name='正式名称'),
        ),
        migrations.AddField(
            model_name='client',
            name='postal_code',
            field=models.CharField(blank=True, help_text='郵便番号（例：123-4567）', max_length=10, null=True, verbose_name='郵便番号'),
        ),
        migrations.AddField(
            model_name='client',
            name='prefecture',
            field=models.CharField(blank=True, help_text='都道府県名', max_length=20, null=True, verbose_name='都道府県'),
        ),
        migrations.AddField(
            model_name='client',
            name='priority',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], help_text='取引優先度（A：高、B：中、C：低）', max_length=1, null=True, verbose_name='優先度'),
        ),
        migrations.AddField(
            model_name='client',
            name='representative',
            field=models.CharField(blank=True, help_text='代表取締役名など', max_length=100, null=True, verbose_name='代表者名'),
        ),
        migrations.AddField(
            model_name='client',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='タグ配列（例：["大手", "継続取引"]）', verbose_name='タグ'),
        ),
        migrations.AddField(
            model_name='client',
            name='website',
            field=models.URLField(blank=True, help_text='公式ウェブサイトURL', max_length=500, null=True, verbose_name='ウェブサイト'),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, help_text='番地、ビル名、階数など', max_length=300, null=True, verbose_name='番地・ビル名'),
        ),
        migrations.AlterField(
            model_name='client',
            name='company_name',
            field=models.CharField(db_index=True, help_text='会社名（通称）', max_length=200, verbose_name='会社名'),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='クライアント登録日時', verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(help_text='代表メールアドレス', max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='client',
            name='industry',
            field=models.CharField(blank=True, choices=[('it', 'IT・通信'), ('manufacturing', '製造'), ('finance', '金融'), ('retail', '小売'), ('service', 'サービス'), ('construction', '建設'), ('real_estate', '不動産'), ('transportation', '運輸'), ('education', '教育'), ('healthcare', '医療・福祉'), ('media', 'メディア'), ('other', 'その他')], db_index=True, help_text='業種カテゴリ', max_length=50, null=True, verbose_name='業種'),
        ),
        migrations.AlterField(
            model_name='client',
            name='note',
            field=models.TextField(blank=True, help_text='その他備考', null=True, verbose_name='備考'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, help_text='代表電話番号', max_length=50, null=True, verbose_name='電話番号'),
        ),
        migrations.AlterField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='最終更新日時', verbose_name='更新日時'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['company_name'], name='clients_company_570f91_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['industry', '-created_at'], name='clients_industr_ad6122_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['priority', '-created_at'], name='clients_priorit_e946b2_idx'),
        ),
    ]
