# Generated by Django 5.0 on 2025-11-16 10:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_remove_client_name_client_ai_confidence_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, help_text='代表メールアドレス', max_length=254, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='メールアドレス'),
        ),
    ]
