# Generated by Django 5.0 on 2025-11-13 13:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('description', models.TextField(verbose_name='説明')),
                ('status', models.CharField(choices=[('todo', '未着手'), ('in-progress', '進行中'), ('review', 'レビュー中'), ('done', '完了'), ('blocked', 'ブロック')], default='todo', max_length=20, verbose_name='ステータス')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('urgent', '緊急')], default='medium', max_length=20, verbose_name='優先度')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='期限')),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='見積時間')),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='実績時間')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='members.member', verbose_name='担当者')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to='members.member', verbose_name='作成者')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project', verbose_name='案件')),
            ],
            options={
                'verbose_name': 'タスク',
                'verbose_name_plural': 'タスク',
                'db_table': 'tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
