# Generated by Django 5.0 on 2025-11-15 15:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_avatar_alter_member_department_and_more'),
        ('projects', '0004_alter_project_options_alter_attachment_file_name_and_more'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='actual_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='実績時間(任意)', max_digits=6, null=True, verbose_name='実績時間'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assignee',
            field=models.ForeignKey(blank=True, help_text='タスクの担当者(任意)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='members.member', verbose_name='担当者'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='作成日時', verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(help_text='タスク作成者', on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to='members.member', verbose_name='作成者'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(help_text='タスクの詳細説明', verbose_name='説明'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, help_text='タスクの期限(任意)', null=True, verbose_name='期限'),
        ),
        migrations.AlterField(
            model_name='task',
            name='estimated_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='見積もり時間(任意)', max_digits=6, null=True, verbose_name='見積時間'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('urgent', '緊急')], default='medium', help_text='タスクの優先度', max_length=20, verbose_name='優先度'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(help_text='関連するプロジェクト', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project', verbose_name='案件'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', '未着手'), ('in-progress', '進行中'), ('review', 'レビュー中'), ('done', '完了'), ('blocked', 'ブロック')], default='todo', help_text='タスクのステータス', max_length=20, verbose_name='ステータス'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(help_text='タスク名(最大200文字)', max_length=200, verbose_name='タイトル'),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='最終更新日時', verbose_name='更新日時'),
        ),
    ]
