# Generated by Django 5.0 on 2025-11-13 13:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='担当者名')),
                ('company_name', models.CharField(max_length=200, verbose_name='会社名')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='電話番号')),
                ('address', models.TextField(blank=True, null=True, verbose_name='住所')),
                ('industry', models.CharField(blank=True, choices=[('it', 'IT・通信'), ('manufacturing', '製造'), ('finance', '金融'), ('retail', '小売'), ('service', 'サービス'), ('other', 'その他')], max_length=20, null=True, verbose_name='業種')),
                ('note', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'クライアント',
                'verbose_name_plural': 'クライアント',
                'db_table': 'clients',
                'ordering': ['-created_at'],
            },
        ),
    ]
