# Generated by Django 5.0 on 2025-11-15 15:20

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_remove_client_name_client_ai_confidence_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(db_index=True, help_text='契約番号（ユニーク）', max_length=50, unique=True, verbose_name='契約番号')),
                ('contract_name', models.CharField(help_text='契約名称', max_length=200, verbose_name='契約名')),
                ('contract_type', models.CharField(choices=[('monthly', '月額契約'), ('annual', '年額契約'), ('project', 'プロジェクトベース'), ('maintenance', '保守契約'), ('other', 'その他')], help_text='契約の種類', max_length=20, verbose_name='契約タイプ')),
                ('status', models.CharField(choices=[('quote', '見積中'), ('active', '契約中'), ('suspended', '休止中'), ('terminated', '終了'), ('cancelled', 'キャンセル')], db_index=True, default='quote', help_text='契約ステータス', max_length=20, verbose_name='ステータス')),
                ('start_date', models.DateField(help_text='契約の開始日', verbose_name='契約開始日')),
                ('end_date', models.DateField(blank=True, help_text='契約の終了日（未定の場合は空）', null=True, verbose_name='契約終了日')),
                ('renewal_date', models.DateField(blank=True, help_text='契約更新予定日', null=True, verbose_name='次回更新日')),
                ('contract_amount', models.DecimalField(decimal_places=2, help_text='契約金額（税込）', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='契約金額')),
                ('billing_cycle', models.CharField(blank=True, choices=[('monthly', '月次'), ('quarterly', '四半期'), ('semi_annual', '半期'), ('annual', '年次'), ('one_time', '一回払い')], help_text='請求頻度', max_length=20, verbose_name='請求サイクル')),
                ('payment_terms', models.CharField(blank=True, help_text='支払条件（例：月末締め翌月末払い）', max_length=100, verbose_name='支払条件')),
                ('payment_method', models.CharField(blank=True, choices=[('bank_transfer', '銀行振込'), ('credit_card', 'クレジットカード'), ('invoice', '請求書払い'), ('direct_debit', '口座振替'), ('other', 'その他')], help_text='支払方法', max_length=50, verbose_name='支払方法')),
                ('billing_address', models.TextField(blank=True, help_text='請求書送付先住所', verbose_name='請求先住所')),
                ('billing_contact', models.CharField(blank=True, help_text='請求書宛名・担当者', max_length=100, verbose_name='請求先担当者')),
                ('sla_level', models.CharField(blank=True, choices=[('standard', 'スタンダード'), ('business', 'ビジネス'), ('premium', 'プレミアム'), ('enterprise', 'エンタープライズ')], help_text='サービスレベル合意レベル', max_length=20, null=True, verbose_name='SLAレベル')),
                ('auto_renewal', models.BooleanField(default=False, help_text='契約期間満了時に自動更新するか', verbose_name='自動更新')),
                ('note', models.TextField(blank=True, help_text='契約に関する備考', null=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='契約登録日時', verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='最終更新日時', verbose_name='更新日時')),
                ('client', models.ForeignKey(help_text='契約先クライアント', on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='clients.client', verbose_name='クライアント')),
            ],
            options={
                'verbose_name': '契約',
                'verbose_name_plural': '契約',
                'db_table': 'contracts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['contract_number'], name='contracts_contrac_bb0c23_idx'), models.Index(fields=['client', 'status'], name='contracts_client__5bbafa_idx'), models.Index(fields=['status', '-start_date'], name='contracts_status_11922e_idx')],
            },
        ),
    ]
