# Generated by Django 5.0 on 2025-11-15 15:20

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_remove_client_name_client_ai_confidence_score_and_more'),
        ('members', '0002_alter_member_avatar_alter_member_department_and_more'),
        ('projects', '0003_alter_project_description'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name': 'プロジェクト', 'verbose_name_plural': 'プロジェクト'},
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file_name',
            field=models.CharField(help_text='アップロードされたファイルの名前', max_length=255, verbose_name='ファイル名'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file_size',
            field=models.BigIntegerField(help_text='ファイルサイズ(バイト単位)', verbose_name='ファイルサイズ'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file_type',
            field=models.CharField(help_text='ファイルのMIMEタイプ(例: application/pdf)', max_length=100, verbose_name='ファイルタイプ'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='project',
            field=models.ForeignKey(help_text='添付ファイルが属するプロジェクト', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='projects.project', verbose_name='プロジェクト'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='ファイルがアップロードされた日時', verbose_name='アップロード日時'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='uploaded_by',
            field=models.ForeignKey(help_text='ファイルをアップロードしたメンバー', null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.member', verbose_name='アップロード者'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='url',
            field=models.URLField(help_text='ファイルのアクセスURL', max_length=500, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(help_text='コメントを投稿したメンバー', on_delete=django.db.models.deletion.CASCADE, to='members.member', verbose_name='投稿者'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(help_text='コメントの内容', verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='コメント作成日時', verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='project',
            field=models.ForeignKey(help_text='コメントが属するプロジェクト', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projects.project', verbose_name='プロジェクト'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='task',
            field=models.ForeignKey(blank=True, help_text='コメントが属するタスク(任意)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tasks.task', verbose_name='タスク'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='コメント最終更新日時', verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='プロジェクト予算(円)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='予算'),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(help_text='プロジェクトのクライアント', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='clients.client', verbose_name='クライアント'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='プロジェクト作成日時', verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, default='', help_text='プロジェクトの詳細説明', verbose_name='説明'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(help_text='プロジェクト終了予定日', verbose_name='終了日'),
        ),
        migrations.AlterField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='プロジェクトメンバー', related_name='projects', to='members.member', verbose_name='メンバー'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text='プロジェクトの識別名(最大200文字)', max_length=200, verbose_name='プロジェクト名'),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='プロジェクトオーナー', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_projects', to='members.member', verbose_name='オーナー'),
        ),
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('urgent', '緊急')], db_index=True, default='medium', help_text='プロジェクトの優先度', max_length=20, verbose_name='優先度'),
        ),
        migrations.AlterField(
            model_name='project',
            name='progress',
            field=models.IntegerField(default=0, help_text='プロジェクト進捗率(0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='進捗率'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(help_text='プロジェクト開始予定日', verbose_name='開始日'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('planning', '計画中'), ('active', '進行中'), ('on-hold', '保留'), ('completed', '完了'), ('cancelled', '中止')], db_index=True, default='planning', help_text='プロジェクトの現在のステータス', max_length=20, verbose_name='ステータス'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='プロジェクトタグ', verbose_name='タグ'),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='最終更新日時', verbose_name='更新日時'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['project', '-uploaded_at'], name='attachments_project_e1d556_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['project', 'created_at'], name='comments_project_7329f9_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['task', 'created_at'], name='comments_task_id_62c144_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', '-created_at'], name='projects_status_1ff00e_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['priority', '-created_at'], name='projects_priorit_c60208_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['start_date', 'end_date'], name='projects_start_d_cb24a6_idx'),
        ),
    ]
