# Generated by Django 5.0 on 2025-11-15 15:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='avatar',
            field=models.ImageField(blank=True, help_text='プロフィール画像(任意)', null=True, upload_to='avatars/', verbose_name='アバター'),
        ),
        migrations.AlterField(
            model_name='member',
            name='department',
            field=models.CharField(blank=True, help_text='所属部署(任意)', max_length=100, null=True, verbose_name='部署'),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(help_text='メンバーのメールアドレス(ユニークキー)', max_length=254, unique=True, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='member',
            name='joined_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='入社日時', verbose_name='参加日時'),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(help_text='メンバーの氏名', max_length=100, verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='member',
            name='position',
            field=models.CharField(blank=True, help_text='役職(任意)', max_length=100, null=True, verbose_name='役職'),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('owner', 'オーナー'), ('admin', '管理者'), ('member', 'メンバー'), ('viewer', '閲覧者')], default='member', help_text='システム上の役割(owner/admin/member/viewer)', max_length=20, verbose_name='役割'),
        ),
        migrations.AlterField(
            model_name='member',
            name='skills',
            field=models.JSONField(blank=True, default=list, help_text='スキルセット(JSON配列形式)', verbose_name='スキル'),
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.OneToOneField(help_text='Django標準認証ユーザー(1対1関係)', on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
